### ISSUE TITLE
how to generate device id automatically ?

### ISSUE THREAD

**Issue by changchichung** [le9i0nx/ansible-syncthing#23]
in group_vars , you define device id

```
device_moto:
  - id: "0000000-0000000-0000000-0000000-0000000-0000000-0000000-0000000"
    name: "tapik"
```
but can you get the id without manually config in devices ?
when the node is a whole new device ( never install syncthing before ) , I don't know how to generate the id .

**Comment by le9i0nx** [comment]
In this case, the id is used to connect devices that are not managed by ansible

**Comment by le9i0nx** [comment]
```
role_syncthing_data:
  folders:
    - inventory_hosts: '{{ groups.homes }}'
      path: '/home/user/crypt/'
      id: 'crypt'
```
this config will set up the crypt folder on the homes group at the specified path and read the id of all devices and link them.
